"""User-facing strings for the Workspace module."""

NAV_TITLE = "Workspaces"
MENU = "Workspace"
ACTION_REFRESH = "Refresh Workspaces"
ACTION_VERIFY = "Verify Workspaces"
NAME_PLACEHOLDER = "New workspace name"
NAME_LABEL = "Workspace name"
BUTTON_CREATE = "Create"
BUTTON_VERIFY = "Verify all"
BUTTON_CANCEL = "Cancel"
STATUS_CREATED = "Workspace '{name}' created"
STATUS_VERIFIED = "Verified {checked} workspace(s): {problems} problem(s)"
STATUS_VERIFY_CANCELLED = "Verification cancelled"
LIST_LABEL = "Workspace list"
